- name: show-neofetch-info.yml --- playbook--- template
  hosts: all
  job_template:
    name: "show-neofetch-info.yml --- playbook--- template"
    job_type: "run"
    organization: "Default"
    inventory: "	lab-server Inventory"
    project: "GitHub Project"
    playbook: "show-neofetch-info.yml"
    credentials:
      - "lab-server Credential"
    state: "present"
    controller_config_file: "~/tower_cli.cfg"
    survey_enabled: yes
    survey_spec: "{{ lookup('file', 'my_survey.json') }}"
