- name: create_template_from_existing.yml
  hosts: all
  gather_facts: false
  tasks:
    - name: Copy Job Template
      job_template:
        name: copy job template
        copy_from: show-neofetch-info.yml --- playbook--- template
        job_type: "run"
        inventory: Copy show-neofetch-info.yml --- playbook--- template
        project: test
        playbook: playbook/show-neofetch-info.yml
        state: "present"