- name: create_template_from_existing.yml
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Copy Job Template
      job_template:
        name: copy-show-neofetch-info.yml --- playbook--- template
        copy_from: show-neofetch-info.yml --- playbook--- template
        job_type: "run"
        inventory: Lab Inventory
        project: GitHub Project
        playbook: show-neofetch-info.yml
        state: "present"