---
- name: Create Job Template on local AWX
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    awx_host: "https://formerly-select-lizard.ngrok-free.app"      # Twój lokalny AWX
    awx_token: "jWGjPDdQYsx478DgcWQoPqZnuTqvx5"            # Twój token AWX
    template_name: "MyLocalTemplate"       # Nazwa tworzonego Job Template
    inventory_name: "localhost"            # Istniejące Inventory
    credential_name: "localhost Credential"  # Istniejące Credential
    playbook_name: "show-neofetch-info.yml"       # Playbook z projektu, który chcesz uruchomić
  tasks:
    - name: Create Job Template
      awx.awx.job_template:
        name: "{{ template_name }}"
        project: "show-neofetch-info.yml --- playbook--- template"
        playbook: "{{ playbook_name }}"
        inventory: "{{ inventory_name }}"
        credential: "{{ credential_name }}"
        state: present
        tower_host: "{{ awx_host }}"
        tower_oauthtoken: "{{ awx_token }}"
      register: result

    - name: Show result
      debug:
        var: result
