---
- name: Create AWX Job Template
  hosts: localhost
  gather_facts: false
  vars:
    awx_host: "https://formerly-select-lizard.ngrok-free.app"
    awx_username: "admin"
    awx_password: "19091974"
    template_name: "copy-show-neofetch-info.yml --- playbook--- template"
    project_name: "	GitHub Project"
    inventory_name: "lab-server Inventory"
    playbook_name: "playbook/show-neofetch-info.yml"

  tasks:
    - name: Get project ID
      awx.awx.tower_project_info:
        host: "{{ awx_host }}"
        username: "{{ awx_username }}"
        password: "{{ awx_password }}"
      register: project_info

    - name: Get inventory ID
      awx.awx.tower_inventory_info:
        host: "{{ awx_host }}"
        username: "{{ awx_username }}"
        password: "{{ awx_password }}"
      register: inventory_info

    - name: Create job template
      awx.awx.tower_job_template:
        host: "{{ awx_host }}"
        username: "{{ awx_username }}"
        password: "{{ awx_password }}"
        name: "{{ template_name }}"
        project: "{{ (project_info.projects | selectattr('name','equalto',project_name) | list)[0].id }}"
        inventory: "{{ (inventory_info.inventories | selectattr('name','equalto',inventory_name) | list)[0].id }}"
        playbook: "{{ playbook_name }}"
        state: present
