- name: create_template_from_existing.yml
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Copy Job Template
      community.general.tower_job_template:
        name: copy-show-neofetch-info
        copy_from: show-neofetch-info
        job_type: run
        inventory: Lab Inventory
        project: GitHub Project
        playbook: show-neofetch-info.yml
        state: present
